class AirportsList {
  static const List<String> airports = [
    "Indira Gandhi International Airport, New Delhi, Delhi, India",
    "Chhatrapati Shivaji Maharaj International Airport, Mumbai, Maharashtra, India",
    "Kempegowda International Airport, Bengaluru, Karnataka, India",
    "Rajiv Gandhi International Airport, Hyderabad, Telangana, India",
    "Chennai International Airport, Chennai, Tamil Nadu, India",
    "Netaji Subhas Chandra Bose International Airport, Kolkata, West Bengal, India",
    "Cochin International Airport, Kochi, Kerala, India",
    "Sardar Vallabhbhai Patel International Airport, Ahmedabad, Gujarat, India",
    "Pune Airport, Pune, Maharashtra, India",
    "Goa International Airport, Vasco da Gama, Goa, India",
    "Manohar International Airport, North Goa, Goa, India",
    "Surat Airport, Surat, Gujarat, India",
    "Vadodara Airport, Vadodara, Gujarat, India",
    "Rajkot Airport, Rajkot, Gujarat, India",
    "Bhavnagar Airport, Bhavnagar, Gujarat, India",
    "Jamnagar Airport, Jamnagar, Gujarat, India",
    "Porbandar Airport, Porbandar, Gujarat, India",
    "Kandla Airport, Kutch, Gujarat, India",
    "Mundra Airport, Kutch, Gujarat, India",
    "Nagpur Airport, Nagpur, Maharashtra, India",
    "Shirdi Airport, Shirdi, Maharashtra, India",
    "Aurangabad Airport, Aurangabad, Maharashtra, India",
    "Kolhapur Airport, Kolhapur, Maharashtra, India",
    "Solapur Airport, Solapur, Maharashtra, India",
    "Akola Airport, Akola, Maharashtra, India",
    "Jalgaon Airport, Jalgaon, Maharashtra, India",
    "Nashik Airport, Nashik, Maharashtra, India",
    "Sindhudurg Airport, Sindhudurg, Maharashtra, India",
    "Jaipur International Airport, Jaipur, Rajasthan, India",
    "Udaipur Airport, Udaipur, Rajasthan, India",
    "Jodhpur Airport, Jodhpur, Rajasthan, India",
    "Bikaner Airport, Bikaner, Rajasthan, India",
    "Kishangarh Airport, Ajmer, Rajasthan, India",
    "Jaisalmer Airport, Jaisalmer, Rajasthan, India",
    "Lucknow Airport, Lucknow, Uttar Pradesh, India",
    "Varanasi Airport, Varanasi, Uttar Pradesh, India",
    "Prayagraj Airport, Prayagraj, Uttar Pradesh, India",
    "Gorakhpur Airport, Gorakhpur, Uttar Pradesh, India",
    "Ayodhya Airport, Ayodhya, Uttar Pradesh, India",
    "Bareilly Airport, Bareilly, Uttar Pradesh, India",
    "Agra Airport, Agra, Uttar Pradesh, India",
    "Kanpur Airport, Kanpur, Uttar Pradesh, India",
    "Aligarh Airport, Aligarh, Uttar Pradesh, India",
    "Mangaluru International Airport, Mangaluru, Karnataka, India",
    "Hubli Airport, Hubballi, Karnataka, India",
    "Belagavi Airport, Belagavi, Karnataka, India",
    "Mysuru Airport, Mysuru, Karnataka, India",
    "Shivamogga Airport, Shivamogga, Karnataka, India",
    "Kalaburagi Airport, Kalaburagi, Karnataka, India",
    "Trivandrum International Airport, Thiruvananthapuram, Kerala, India",
    "Calicut International Airport, Kozhikode, Kerala, India",
    "Kannur International Airport, Kannur, Kerala, India",
    "Coimbatore International Airport, Coimbatore, Tamil Nadu, India",
    "Madurai Airport, Madurai, Tamil Nadu, India",
    "Tiruchirappalli Airport, Tiruchirappalli, Tamil Nadu, India",
    "Salem Airport, Salem, Tamil Nadu, India",
    "Thoothukudi Airport, Thoothukudi, Tamil Nadu, India",
    "Vellore Airport, Vellore, Tamil Nadu, India",
    "Biju Patnaik International Airport, Bhubaneswar, Odisha, India",
    "Jharsuguda Airport, Jharsuguda, Odisha, India",
    "Rourkela Airport, Rourkela, Odisha, India",
    "Utkela Airport, Bhawanipatna, Odisha, India",
    "Bagdogra Airport, Siliguri, West Bengal, India",
    "Durgapur Airport, Durgapur, West Bengal, India",
    "Cooch Behar Airport, Cooch Behar, West Bengal, India",
    "Lokpriya Gopinath Bordoloi International Airport, Guwahati, Assam, India",
    "Dibrugarh Airport, Dibrugarh, Assam, India",
    "Silchar Airport, Silchar, Assam, India",
    "Tezpur Airport, Tezpur, Assam, India",
    "Jorhat Airport, Jorhat, Assam, India",
    "Imphal Airport, Imphal, Manipur, India",
    "Agartala Airport, Agartala, Tripura, India",
    "Aizawl Airport, Aizawl, Mizoram, India",
    "Dimapur Airport, Dimapur, Nagaland, India",
    "Itanagar Airport, Itanagar, Arunachal Pradesh, India",
    "Pasighat Airport, Pasighat, Arunachal Pradesh, India",
    "Chandigarh International Airport, Chandigarh, India",
    "Amritsar Airport, Amritsar, Punjab, India",
    "Bathinda Airport, Bathinda, Punjab, India",
    "Dehradun Airport, Dehradun, Uttarakhand, India",
    "Pantnagar Airport, Pantnagar, Uttarakhand, India",
    "Shimla Airport, Shimla, Himachal Pradesh, India",
    "Kangra Airport, Dharamshala, Himachal Pradesh, India",
    "Srinagar Airport, Srinagar, Jammu & Kashmir, India",
    "Jammu Airport, Jammu, Jammu & Kashmir, India",
    "Leh Airport, Leh, Ladakh, India",
    "Indore Airport, Indore, Madhya Pradesh, India",
    "Bhopal Airport, Bhopal, Madhya Pradesh, India",
    "Jabalpur Airport, Jabalpur, Madhya Pradesh, India",
    "Gwalior Airport, Gwalior, Madhya Pradesh, India",
    "Khajuraho Airport, Khajuraho, Madhya Pradesh, India",
    "Veer Savarkar International Airport, Port Blair, Andaman & Nicobar Islands, India",
    "Shravasti Airport, Shravasti, Uttar Pradesh, India",
    "Chitrakoot Airport, Chitrakoot, Uttar Pradesh, India",
    "Azamgarh Airport, Azamgarh, Uttar Pradesh, India",
    "Moradabad Airport, Moradabad, Uttar Pradesh, India",
    "Purnea Airport, Purnea, Bihar, India",
    "Raxaul Airport, Raxaul, Bihar, India",
    "Deoghar Airport, Deoghar, Jharkhand, India",
    "Bokaro Airport, Bokaro, Jharkhand, India",
    "Jagdalpur Airport, Jagdalpur, Chhattisgarh, India",
    "Ambikapur Airport, Ambikapur, Chhattisgarh, India",
    "Jeypore Airport, Jeypore, Odisha, India",
    "Rairangpur Airport, Rairangpur, Odisha, India",
    "Barmer Airport, Barmer, Rajasthan, India",
    "Bhilwara Airport, Bhilwara, Rajasthan, India",
    "Ratnagiri Airport, Ratnagiri, Maharashtra, India",
    "Gondia Airport, Gondia, Maharashtra, India",
    "Amravati Airport, Amravati, Maharashtra, India",
    "Bidar Airport, Bidar, Karnataka, India",
    "Yadgir Airport, Yadgir, Karnataka, India",
    "Donakonda Airport, Donakonda, Andhra Pradesh, India",
    "Puttaparthi Airport, Puttaparthi, Andhra Pradesh, India",
    "Neyveli Airport, Neyveli, Tamil Nadu, India",
    "Ramanathapuram Airport, Ramanathapuram, Tamil Nadu, India",
    "Rupsi Airport, Rupsi, Assam, India",
    "Tezu Airport, Tezu, Arunachal Pradesh, India",
    "Ziro Airport, Ziro, Arunachal Pradesh, India",
    "Daporijo Airport, Daporijo, Arunachal Pradesh, India",
    "Car Nicobar Airport, Car Nicobar, Andaman & Nicobar Islands, India",
    "Campbell Bay Airport, Great Nicobar, India",
  ];
}
